### ISSUE TITLE
Initial Trails leads to 404

### ISSUE THREAD

**Issue by stewsmith** [thoughtbot/trail-map#168]
To reproduce:
 1) Visit https://robots.thoughtbot.com/trail-map
 2) Click on any of the Initial Trails
 3) 404

**Comment by adarsh** [comment]
We are no longer maintaining this repository. See 17008082810ba2d86ff71e29679f2de044d5c04d

I've reported the broken links to the appropriate people - thank you for letting us know.

You can get the trail content on upcase.com now.

**Comment by jferris** [comment]
As of ecd0474b423ff93953ae79e4c90e8d91b152bafa, we've decided to keep these around separately as a community-driven effort.

**Comment by jferris** [comment]
@stewsmith thanks for reporting! The links in that blog post have been fixed: https://robots.thoughtbot.com/trail-map
